(defclass math ()
  ((add :accessor vector3-add :initarg :add :initform #'+ :allocation :class)
   (sub :accessor vector3-sub :initarg :sub :initform #'- :allocation :class)
   (mult :accessor vector3-mult :initarg :mult :initform #'* :allocation :class)
   (div :accessor vector3-div :initarg :div :initform #'/ :allocation :class)
   (sqrt :accessor vector3-sqrt :initarg :sqrt :initform #'sqrt :allocation :class))
)

(defclass math-ad (math)
  ((add :initform #'ad-+ :allocation :class)
   (sub :initform #'ad-- :allocation :class)
   (mult :initform #'ad-* :allocation :class)
   (div :initform #'ad-/ :allocation :class)
   (sqrt :initform #'ad-sqrt :allocation :class))
)
